from base64 import b64encode
from io import BytesIO
from json import dumps
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "supabase" / "functions" / "social-card" / "poster-art.generated.ts"
SOURCES = {
    "loss": ROOT / "assets" / "loss" / "wojak-meltdown.webp",
    "victory": ROOT / "assets" / "victory" / "winning-son.webp",
}


def jpeg_data_url(path: Path) -> str:
    output = BytesIO()
    with Image.open(path) as image:
        image.convert("RGB").save(output, "JPEG", quality=82, optimize=True, progressive=True)
    return "data:image/jpeg;base64," + b64encode(output.getvalue()).decode("ascii")


data = {kind: jpeg_data_url(path) for kind, path in SOURCES.items()}
OUTPUT.write_text(
    "// Generated by scripts/generate-poster-art-module.py. Do not edit by hand.\n"
    f"export const POSTER_ART_DATA = {dumps(data, separators=(',', ':'))} as const;\n",
    encoding="utf-8",
)
print(f"Generated {OUTPUT}")
