-- Composite Operator Ledger
-- Initial auth, public profiles, setup records, metrics, and row-level security.

begin;

create extension if not exists citext with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create type public.setup_direction as enum ('LONG', 'SHORT');
create type public.setup_horizon as enum ('DAY_TRADE', 'SWING', 'POSITION', 'LONG_TERM');
create type public.setup_trigger as enum ('BREACH', 'PULLBACK', 'MARKET');
create type public.setup_status as enum (
  'NEW',
  'QUEUED',
  'WATCHING',
  'NEAR',
  'HOT',
  'MISSED',
  'ACTIVE',
  'T1_HIT',
  'T2_HIT',
  'T3_HIT',
  'STOPPED',
  'CANCELLED',
  'EXPIRED',
  'CLOSED',
  'RESOLVED'
);
create type public.setup_final_status as enum ('STOPPED', 'T1', 'T2', 'T3', 'CANCELLED', 'EXPIRED');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  handle extensions.citext not null unique,
  display_name text not null,
  avatar_url text,
  bio text not null default '',
  preferred_provider text not null default 'unknown',
  x_username text,
  is_public boolean not null default true,
  account_status text not null default 'ACTIVE' check (account_status in ('ACTIVE', 'SUSPENDED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_handle_shape check (handle::text ~ '^[a-z0-9][a-z0-9_-]{2,29}$'),
  constraint profiles_display_name_length check (char_length(display_name) between 1 and 80),
  constraint profiles_bio_length check (char_length(bio) <= 600)
);

create table public.setups (
  id bigint generated by default as identity primary key,
  public_id uuid not null default extensions.gen_random_uuid() unique,
  client_request_id uuid not null unique,
  user_id uuid not null references public.profiles(id) on delete restrict,
  ticker text not null,
  direction public.setup_direction not null,
  horizon public.setup_horizon not null default 'SWING',
  trigger_type public.setup_trigger not null,
  entry numeric(24, 8) not null,
  stop numeric(24, 8) not null,
  t1 numeric(24, 8) not null,
  t2 numeric(24, 8),
  t3 numeric(24, 8),
  strategy text,
  thesis text,
  status public.setup_status not null default 'QUEUED',
  current_price numeric(24, 8),
  price_source text,
  pct_from_fill numeric(18, 8),
  r_result numeric(18, 8),
  score numeric(18, 8),
  final_status public.setup_final_status,
  submitted_at timestamptz not null default now(),
  triggered_at timestamptz,
  t1_hit_at timestamptz,
  t2_hit_at timestamptz,
  t3_hit_at timestamptz,
  stop_hit_at timestamptz,
  archived_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint setups_ticker_shape check (ticker ~ '^[A-Z0-9.^=_-]{1,16}$'),
  constraint setups_prices_positive check (
    entry > 0 and stop > 0 and t1 > 0 and
    (t2 is null or t2 > 0) and
    (t3 is null or t3 > 0)
  ),
  constraint setups_long_geometry check (
    direction <> 'LONG' or (
      stop < entry and
      t1 > entry and
      (t2 is null or t2 > t1) and
      (t3 is null or t3 > coalesce(t2, t1))
    )
  ),
  constraint setups_short_geometry check (
    direction <> 'SHORT' or (
      stop > entry and
      t1 < entry and
      (t2 is null or t2 < t1) and
      (t3 is null or t3 < coalesce(t2, t1))
    )
  ),
  constraint setups_strategy_length check (strategy is null or char_length(strategy) <= 80),
  constraint setups_thesis_length check (thesis is null or char_length(thesis) <= 1200)
);

create table public.setup_events (
  id bigint generated always as identity primary key,
  setup_id bigint not null references public.setups(id) on delete cascade,
  event_type text not null,
  event_at timestamptz not null default now(),
  price numeric(24, 8),
  payload jsonb not null default '{}'::jsonb,
  created_by text not null default 'SYSTEM'
);

create table public.trader_metrics (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  total_setups bigint not null default 0,
  triggered_setups bigint not null default 0,
  stopped_setups bigint not null default 0,
  t1_hits bigint not null default 0,
  t2_hits bigint not null default 0,
  t3_hits bigint not null default 0,
  win_rate numeric(18, 8),
  avg_pct_from_fill numeric(18, 8),
  avg_r numeric(18, 8),
  total_score numeric(18, 8) not null default 0,
  goat_score numeric(18, 8),
  last_30d_score numeric(18, 8) not null default 0,
  refreshed_at timestamptz not null default now()
);

create index setups_user_submitted_idx on public.setups (user_id, submitted_at desc);
create index setups_status_submitted_idx on public.setups (status, submitted_at desc);
create index setups_ticker_submitted_idx on public.setups (ticker, submitted_at desc);
create index setups_open_state_idx on public.setups (submitted_at desc)
  where status in ('QUEUED', 'WATCHING', 'NEAR', 'HOT', 'ACTIVE', 'T1_HIT', 'T2_HIT');
create index setup_events_setup_time_idx on public.setup_events (setup_id, event_at desc);
create index trader_metrics_goat_idx on public.trader_metrics (goat_score desc nulls last, triggered_setups desc);
create index trader_metrics_30d_idx on public.trader_metrics (last_30d_score desc, triggered_setups desc);
create index trader_metrics_score_idx on public.trader_metrics (total_score desc, triggered_setups desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

create trigger setups_touch_updated_at
before update on public.setups
for each row execute function public.touch_updated_at();

create or replace function public.allocate_profile_handle(
  user_id uuid,
  metadata jsonb
)
returns extensions.citext
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_value text;
  base_handle text;
  candidate text;
begin
  source_value := coalesce(
    metadata ->> 'user_name',
    metadata ->> 'preferred_username',
    metadata ->> 'full_name',
    metadata ->> 'name',
    'operator'
  );

  base_handle := lower(regexp_replace(source_value, '[^a-zA-Z0-9_-]+', '-', 'g'));
  base_handle := trim(both '-' from base_handle);
  base_handle := left(base_handle, 23);

  if char_length(base_handle) < 3 then
    base_handle := 'operator';
  end if;

  candidate := base_handle;
  if exists (select 1 from public.profiles where handle = candidate::extensions.citext) then
    candidate := left(base_handle, 23) || '-' || left(replace(user_id::text, '-', ''), 6);
  end if;

  return candidate::extensions.citext;
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_handle extensions.citext;
  display_value text;
  provider_value text;
begin
  new_handle := public.allocate_profile_handle(new.id, coalesce(new.raw_user_meta_data, '{}'::jsonb));
  display_value := left(coalesce(
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'name',
    new.raw_user_meta_data ->> 'user_name',
    new_handle::text
  ), 80);
  provider_value := coalesce(new.raw_app_meta_data ->> 'provider', 'unknown');

  insert into public.profiles (
    id,
    handle,
    display_name,
    avatar_url,
    preferred_provider,
    x_username
  ) values (
    new.id,
    new_handle,
    display_value,
    coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture'),
    provider_value,
    case when provider_value in ('x', 'twitter') then new.raw_user_meta_data ->> 'user_name' else null end
  )
  on conflict (id) do nothing;

  insert into public.trader_metrics (profile_id)
  values (new.id)
  on conflict (profile_id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.prevent_setup_core_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.user_id is distinct from new.user_id
    or old.ticker is distinct from new.ticker
    or old.direction is distinct from new.direction
    or old.horizon is distinct from new.horizon
    or old.trigger_type is distinct from new.trigger_type
    or old.entry is distinct from new.entry
    or old.stop is distinct from new.stop
    or old.t1 is distinct from new.t1
    or old.t2 is distinct from new.t2
    or old.t3 is distinct from new.t3
    or old.strategy is distinct from new.strategy
    or old.thesis is distinct from new.thesis
    or old.submitted_at is distinct from new.submitted_at then
      raise exception 'Core setup fields are immutable after publication.' using errcode = '22000';
  end if;
  return new;
end;
$$;

create trigger setups_prevent_core_mutation
before update on public.setups
for each row execute function public.prevent_setup_core_mutation();

create or replace function public.refresh_trader_metrics(target_profile_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.trader_metrics (
    profile_id,
    total_setups,
    triggered_setups,
    stopped_setups,
    t1_hits,
    t2_hits,
    t3_hits,
    win_rate,
    avg_pct_from_fill,
    avg_r,
    total_score,
    goat_score,
    last_30d_score,
    refreshed_at
  )
  with stats as (
    select
      count(*)::bigint as total_setups,
      count(*) filter (
        where triggered_at is not null
          or status in ('ACTIVE', 'T1_HIT', 'T2_HIT', 'T3_HIT', 'STOPPED', 'CLOSED', 'RESOLVED')
      )::bigint as triggered_setups,
      count(*) filter (where final_status = 'STOPPED' or stop_hit_at is not null)::bigint as stopped_setups,
      count(*) filter (where t1_hit_at is not null or final_status in ('T1', 'T2', 'T3'))::bigint as t1_hits,
      count(*) filter (where t2_hit_at is not null or final_status in ('T2', 'T3'))::bigint as t2_hits,
      count(*) filter (where t3_hit_at is not null or final_status = 'T3')::bigint as t3_hits,
      avg(pct_from_fill) filter (where pct_from_fill is not null)::numeric(18, 8) as avg_pct_from_fill,
      avg(r_result) filter (where r_result is not null)::numeric(18, 8) as avg_r,
      coalesce(sum(score) filter (where score is not null), 0)::numeric(18, 8) as total_score,
      coalesce(sum(score) filter (
        where score is not null and submitted_at >= now() - interval '30 days'
      ), 0)::numeric(18, 8) as last_30d_score
    from public.setups
    where user_id = target_profile_id
  ), scored as (
    select
      *,
      case when total_setups > 0 then t1_hits::numeric / total_setups::numeric else null end as win_rate
    from stats
  )
  select
    target_profile_id,
    total_setups,
    triggered_setups,
    stopped_setups,
    t1_hits,
    t2_hits,
    t3_hits,
    win_rate,
    avg_pct_from_fill,
    avg_r,
    total_score,
    case
      when triggered_setups < 3 then null
      else (
        (greatest(-5::numeric, least(5::numeric, coalesce(avg_r, 0))) * 0.7)
        + (coalesce(win_rate, 0) * 0.3)
      ) * least(1::numeric, triggered_setups::numeric / 20::numeric)
    end,
    last_30d_score,
    now()
  from scored
  on conflict (profile_id) do update set
    total_setups = excluded.total_setups,
    triggered_setups = excluded.triggered_setups,
    stopped_setups = excluded.stopped_setups,
    t1_hits = excluded.t1_hits,
    t2_hits = excluded.t2_hits,
    t3_hits = excluded.t3_hits,
    win_rate = excluded.win_rate,
    avg_pct_from_fill = excluded.avg_pct_from_fill,
    avg_r = excluded.avg_r,
    total_score = excluded.total_score,
    goat_score = excluded.goat_score,
    last_30d_score = excluded.last_30d_score,
    refreshed_at = excluded.refreshed_at;
end;
$$;

create or replace function public.refresh_metrics_after_setup_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_trader_metrics(old.user_id);
    return old;
  end if;

  perform public.refresh_trader_metrics(new.user_id);
  if tg_op = 'UPDATE' and old.user_id is distinct from new.user_id then
    perform public.refresh_trader_metrics(old.user_id);
  end if;
  return new;
end;
$$;

create trigger setups_metrics_after_insert
after insert on public.setups
for each row execute function public.refresh_metrics_after_setup_change();

create trigger setups_metrics_after_delete
after delete on public.setups
for each row execute function public.refresh_metrics_after_setup_change();

create trigger setups_metrics_after_outcome_update
after update of status, triggered_at, t1_hit_at, t2_hit_at, t3_hit_at, stop_hit_at, archived_at, final_status, pct_from_fill, r_result, score
on public.setups
for each row execute function public.refresh_metrics_after_setup_change();

create or replace view public.setups_public
with (security_invoker = true)
as
select
  s.public_id as id,
  s.user_id,
  p.handle::text as handle,
  p.display_name,
  p.avatar_url,
  s.ticker,
  s.direction,
  s.horizon,
  s.trigger_type,
  s.entry,
  s.stop,
  s.t1,
  s.t2,
  s.t3,
  s.strategy,
  s.thesis,
  s.status,
  s.current_price,
  s.price_source,
  s.pct_from_fill,
  s.r_result,
  s.score,
  s.final_status,
  s.submitted_at,
  s.triggered_at,
  s.t1_hit_at,
  s.t2_hit_at,
  s.t3_hit_at,
  s.stop_hit_at,
  s.archived_at,
  s.updated_at
from public.setups s
join public.profiles p on p.id = s.user_id
where p.is_public = true and p.account_status = 'ACTIVE';

create or replace function public.leaderboard_page(
  p_sort text default 'goat',
  p_search text default '',
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  rank_position bigint,
  total_count bigint,
  profile_id uuid,
  handle text,
  display_name text,
  avatar_url text,
  bio text,
  total_setups bigint,
  triggered_setups bigint,
  stopped_setups bigint,
  t1_hits bigint,
  t2_hits bigint,
  t3_hits bigint,
  win_rate numeric,
  avg_pct_from_fill numeric,
  avg_r numeric,
  total_score numeric,
  goat_score numeric,
  last_30d_score numeric
)
language sql
stable
security definer
set search_path = ''
as $$
  with visible as (
    select
      p.id as profile_id,
      p.handle::text as handle,
      p.display_name,
      p.avatar_url,
      p.bio,
      coalesce(m.total_setups, 0)::bigint as total_setups,
      coalesce(m.triggered_setups, 0)::bigint as triggered_setups,
      coalesce(m.stopped_setups, 0)::bigint as stopped_setups,
      coalesce(m.t1_hits, 0)::bigint as t1_hits,
      coalesce(m.t2_hits, 0)::bigint as t2_hits,
      coalesce(m.t3_hits, 0)::bigint as t3_hits,
      m.win_rate,
      m.avg_pct_from_fill,
      m.avg_r,
      coalesce(m.total_score, 0) as total_score,
      m.goat_score,
      coalesce(m.last_30d_score, 0) as last_30d_score
    from public.profiles p
    left join public.trader_metrics m on m.profile_id = p.id
    where p.is_public = true
      and p.account_status = 'ACTIVE'
      and (
        coalesce(p_search, '') = ''
        or p.handle::text ilike '%' || p_search || '%'
        or p.display_name ilike '%' || p_search || '%'
      )
  ), ranked as (
    select
      row_number() over (
        order by
          case when lower(coalesce(p_sort, 'goat')) = 'last30' then last_30d_score end desc nulls last,
          case when lower(coalesce(p_sort, 'goat')) = 'score' then total_score end desc nulls last,
          case when lower(coalesce(p_sort, 'goat')) = 'win' then win_rate end desc nulls last,
          case when lower(coalesce(p_sort, 'goat')) = 'goat' then goat_score end desc nulls last,
          triggered_setups desc,
          handle asc
      ) as rank_position,
      count(*) over () as total_count,
      visible.*
    from visible
  )
  select *
  from ranked
  order by rank_position
  limit least(greatest(coalesce(p_limit, 50), 1), 500)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

alter table public.profiles enable row level security;
alter table public.setups enable row level security;
alter table public.setup_events enable row level security;
alter table public.trader_metrics enable row level security;

create policy profiles_public_read
on public.profiles for select
to anon, authenticated
using (is_public = true or id = auth.uid());

create policy profiles_owner_update
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy setups_public_read
on public.setups for select
to anon, authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = setups.user_id
      and p.is_public = true
      and p.account_status = 'ACTIVE'
  )
  or user_id = auth.uid()
);

create policy setups_owner_insert
on public.setups for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.account_status = 'ACTIVE'
  )
);

create policy metrics_public_read
on public.trader_metrics for select
to anon, authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = trader_metrics.profile_id
      and p.is_public = true
      and p.account_status = 'ACTIVE'
  )
  or profile_id = auth.uid()
);

revoke all on public.profiles from anon, authenticated;
revoke all on public.setups from anon, authenticated;
revoke all on public.setup_events from anon, authenticated;
revoke all on public.trader_metrics from anon, authenticated;

revoke execute on function public.allocate_profile_handle(uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.handle_new_auth_user() from public, anon, authenticated;
revoke execute on function public.prevent_setup_core_mutation() from public, anon, authenticated;
revoke execute on function public.refresh_trader_metrics(uuid) from public, anon, authenticated;
revoke execute on function public.refresh_metrics_after_setup_change() from public, anon, authenticated;
revoke execute on function public.touch_updated_at() from public, anon, authenticated;
revoke execute on function public.leaderboard_page(text, text, integer, integer) from public, anon, authenticated;

grant select on public.profiles to anon, authenticated;
grant update (display_name, avatar_url, bio, is_public) on public.profiles to authenticated;
grant select on public.setups to anon, authenticated;
grant insert (
  client_request_id,
  user_id,
  ticker,
  direction,
  horizon,
  trigger_type,
  entry,
  stop,
  t1,
  t2,
  t3,
  strategy,
  thesis
) on public.setups to authenticated;
grant usage, select on sequence public.setups_id_seq to authenticated;
grant select on public.trader_metrics to anon, authenticated;
grant select on public.setups_public to anon, authenticated;
grant execute on function public.leaderboard_page(text, text, integer, integer) to anon, authenticated;

commit;
